# Generated by Django 2.2.24 on 2022-08-11 23:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220812_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, 
                db_index=True, 
                max_length=128, 
                null=True, 
                region=None, 
                verbose_name='Телефон владельца (нормализованный)'
            ),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(
                max_length=20, 
                verbose_name='Телефон владельца'
            ),
        ),
    ]
