# Generated by Django 2.2.24 on 2022-08-12 00:01

from django.db import migrations
from django.db.models import F
import phonenumbers


def purify_phonenumber(phone):
    try:
        parsed_phone = phonenumbers.parse(phone, 'RU')
    except phonenumbers.phonenumberutil.NumberParseException:
        return None
    if (phonenumbers.is_possible_number(parsed_phone)
        and phonenumbers.is_valid_number(parsed_phone)):
        pure_phone = phonenumbers.format_number(
            parsed_phone,
            phonenumbers.PhoneNumberFormat.E164
        )
        return pure_phone


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(
        owner_pure_phone=purify_phonenumber(F('owners_phonenumber'))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20220812_0255'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
