# Generated by Django 2.2.24 on 2022-08-12 00:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220812_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=200, 
                    verbose_name='ФИО владельца'
                )),
                ('phonenumber', models.CharField(
                    max_length=20, 
                    verbose_name='Телефон владельца'
                )),
                ('pure_phone', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True, 
                    db_index=True, 
                    max_length=128, 
                    null=True, 
                    region=None, 
                    verbose_name='Телефон владельца (нормализованный)'
                )),
                ('flats_owned', models.ManyToManyField(
                    related_name='owners', 
                    to='property.Flat', 
                    verbose_name='Квартиры в собственности'
                )),
            ],
        ),
    ]
