# Generated by Django 2.2.24 on 2022-08-12 12:11

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner.flats_owned.set([flat.id])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220812_1456'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners)
    ]
