# Generated by Django 2.2.24 on 2022-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220812_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats_owned',
            field=models.ManyToManyField(
                db_index=True, 
                related_name='owners', 
                to='property.Flat', 
                verbose_name='Квартиры в собственности'
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(
                db_index=True, 
                max_length=200, 
                verbose_name='ФИО владельца'
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phonenumber',
            field=models.CharField(
                db_index=True, 
                max_length=20, 
                verbose_name='Телефон владельца'
            ),
        ),
    ]
