# Generated by Django 2.2.24 on 2022-08-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220812_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='complaints', 
                to='property.Flat', 
                verbose_name='Квартира, на которую пожаловались'
            ),
        ),
    ]
